# Generated by Django 5.2.5 on 2025-08-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_at',
        ),
    ]
