# Generated by Django 5.2.5 on 2025-09-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('student', 'group')},
        ),
    ]
