# Generated by Django 5.2.5 on 2025-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student_email_ci',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_phone',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
