# Generated by Django 5.2.5 on 2025-09-28 18:32

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='idx_student_email_ci'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(models.F('phone'), name='idx_student_phone'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_student_email_ci'),
        ),
    ]
