# Generated by Django 5.2.5 on 2025-08-24 15:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_unique_student_email_ci_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(models.F('phone'), name='idx_student_phone'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_student_email_ci'),
        ),
    ]
