# Generated by Django 5.2.5 on 2025-09-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stage', models.CharField(choices=[('GRADE6', 'سادس ابتدائي'), ('PREP', 'إعدادي')], max_length=10)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('schedule', models.CharField(max_length=100)),
                ('days', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
