# Generated by Django 5.2.5 on 2025-08-24 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='المجموعات التي ينتمي لها المستخدم', related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف المصري غير صالح. مثال: 01012345678', regex='^01[0-2,5][0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='صلاحيات المستخدم الخاصة', related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
